security:

    # encryptage du mot de passe pour User
    encoders:
        App\Entity\User:
            algorithm:                plaintext
        App\Entity\Praticien:
            algorithm:                plaintext


    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    role_hierarchy:
        ROLE_ASST:                    ROLE_USER
        ROLE_MEDIC:                   ROLE_ASST
        ROLE_ADMIN:                   ROLE_MEDIC

    providers:
        db:
            # les utilisateurs sont les entités User
            entity:
                class:                App\Entity\User
                # Identifiant de Login : l'email du User
                property:             'email'
        ph:
            entity:
                class:     App\Entity\Praticien
                property: 'email_pro'

    firewalls:
        dev:
            pattern:                  ^/(_(profiler|wdt)|css|images|js)/
            security:                 false

        admin:
            anonymous:                true
            pattern:                  ^/adm
            provider:                 db
            form_login:
                login_path:           app_admlogin_login
                check_path:           app_admlogin_login
                default_target_path:  app_admin_dboard_index
                username_parameter:   "adminEmail"
                password_parameter:   "adminMdp"
            logout:
                path:                 app_admin_dboard_logout #app_admlogin_logout
                target:               app_admin_dboard_index

        praticien:
            anonymous:                true
            pattern:                  ^/espace/pr
            provider:                 ph
            form_login:
                login_path:           app_espacepraticienfreezone_index
                check_path:           app_espacepraticienfreezone_index
                default_target_path:  app_espacepraticienloggedin_index
                username_parameter:   "email"
                password_parameter:   "password"
            logout:
                path:                 app_espacepraticienloggedin_logout
                target:               app_espacepraticienfreezone_index

        main:
            anonymous:                true
            pattern:                  ^/
            provider:                 db
            form_login:
                login_path:           app_espacepatientfreezone_login
                check_path:           app_espacepatientfreezone_login
                default_target_path:  app_espacepatientloggedin_index
                username_parameter:   "_username"
                password_parameter:   "_password"
            logout:
                # route définie dans config/routes.yaml
                path:                 app_espacepatientloggedin_logout
                target:               app_espacepatientfreezone_login
                invalidate_session:   false
            # https://symfony.com/doc/current/security/form_login_setup.html



    # Easy way to control access for large sections of your site
    # Note:                           Only the *first* access control that matches will be used
    access_control:
        - { path: ^/admin, roles:     ROLE_ADMIN }

        - { path: ^/espace/patient/logged/in, roles: ROLE_USER } # il faut au minimum le role de ROLE_USER pour y accéder

        - { path: ^/espace/praticien/logged/in, roles: ROLE_MEDIC }
