#index:
#    path:                         /
#    controller:                   App\Controller\DefaultController::index

#route de la page deconnexion
app_espacepatientloggedin_logout:
  path:                            /espace/patient/logged/in/logout

app_admlogin_logout:
  path:                            /admin/dashboard/logout

app_espacepraticienloggedin_logout:
  path:                            /espace/praticien/logged/in/logout

app_espaceassistantloggedin_logout:
  path:                            /espace/assistant/logged/in/logout